Repository googleapis/discovery-artifact-manager, pull requests merged in 2021-09, with the labels that each got.

#2647 chore: autogenerated discovery document update
  discoveries/apigee.v1.json
Labels: cla: yes, automerge

#2648 chore: autogenerated discovery document update
  discoveries/datacatalog.v1.json
Labels: cla: yes, automerge

#2649 chore: autogenerated discovery document update
  discoveries/androidpublisher.v3.json
Labels: cla: yes, automerge

#2650 chore: autogenerated discovery document update
  discoveries/healthcare.v1.json
  discoveries/healthcare.v1beta1.json
Labels: cla: yes, automerge

#2651 chore: autogenerated discovery document update
  discoveries/content.v2.json
Labels: cla: yes, automerge

#2652 chore: autogenerated discovery document update
  discoveries/dialogflow.v2beta1.json
Labels: cla: yes, automerge

#2653 chore: autogenerated discovery document update
  discoveries/dialogflow.v2.json
  discoveries/dialogflow.v3.json
  discoveries/dialogflow.v3beta1.json
Labels: cla: yes, automerge

#2654 chore: autogenerated discovery document update
  discoveries/iam.v1.json
Labels: cla: yes, automerge

#2655 chore: autogenerated discovery document update
  discoveries/containeranalysis.v1alpha1.json
Labels: cla: yes, automerge

#2657 chore: autogenerated discovery document update
  discoveries/index.json
Labels: cla: yes, automerge

#2658 chore: autogenerated discovery document update
  discoveries/ideahub.v1beta.json
  discoveries/jobs.v3p1beta1.json
Labels: cla: yes, automerge

#2659 chore: autogenerated discovery document update
  discoveries/bigquery.v2.json
Labels: cla: yes, automerge

#2660 chore: autogenerated discovery document update
  discoveries/jobs.v3.json
Labels: cla: yes, automerge

#2661 chore: autogenerated discovery document update
  discoveries/content.v2.json
Labels: cla: yes, automerge

#2662 chore: autogenerated discovery document update
  discoveries/appengine.v1.json
  discoveries/appengine.v1alpha.json
  discoveries/appengine.v1beta.json
Labels: cla: yes, automerge

#2663 chore: autogenerated discovery document update
  discoveries/jobs.v4.json
  discoveries/managedidentities.v1.json
  discoveries/monitoring.v3.json
  discoveries/pubsub.v1.json
Labels: cla: yes, automerge

#2664 chore: autogenerated discovery document update
  discoveries/speech.v1.json
  discoveries/speech.v1p1beta1.json
Labels: cla: yes, automerge

#2665 chore: autogenerated discovery document update
  discoveries/container.v1beta1.json
Labels: cla: yes, automerge

#2666 chore: autogenerated discovery document update
  discoveries/contactcenterinsights.v1.json
  discoveries/dataflow.v1b3.json
Labels: cla: yes, automerge

#2667 chore: autogenerated discovery document update
  discoveries/displayvideo.v1.json
Labels: cla: yes, automerge

#2668 chore: autogenerated discovery document update
  discoveries/container.v1.json
Labels: cla: yes, automerge

#2669 chore: autogenerated discovery document update
  discoveries/bigqueryconnection.v1beta1.json
  discoveries/index.json
Labels: cla: yes, automerge

#2670 chore: autogenerated discovery document update
  discoveries/bigqueryconnection.v1beta1.json
  discoveries/index.json
Labels: cla: yes, automerge

#2671 chore: autogenerated discovery document update
  discoveries/bigqueryconnection.v1beta1.json
  discoveries/index.json
Labels: cla: yes, automerge

#2672 chore: autogenerated discovery document update
  discoveries/bigqueryconnection.v1beta1.json
  discoveries/index.json
Labels: cla: yes, automerge

#2673 chore: autogenerated discovery document update
  discoveries/bigqueryconnection.v1beta1.json
  discoveries/index.json
Labels: cla: yes, automerge

#2674 chore: autogenerated discovery document update
  discoveries/gkehub.v1alpha2.json
Labels: cla: yes, automerge

#2675 chore: autogenerated discovery document update
  discoveries/bigqueryconnection.v1beta1.json
  discoveries/index.json
Labels: cla: yes, automerge

#2676 chore: autogenerated discovery document update
  discoveries/compute.beta.json
  discoveries/compute.v1.json
Labels: cla: yes, automerge

#2677 chore: autogenerated discovery document update
  discoveries/compute.alpha.json
Labels: cla: yes, automerge

#2678 chore: autogenerated discovery document update
  discoveries/searchconsole.v1.json
Labels: cla: yes, automerge

#2679 chore: autogenerated discovery document update
  discoveries/assuredworkloads.v1.json
Labels: cla: yes, automerge

#2680 chore: autogenerated discovery document update
  discoveries/recaptchaenterprise.v1.json
Labels: cla: yes, automerge

#2682 chore: autogenerated discovery document update
  discoveries/file.v1beta1.json
Labels: cla: yes, automerge

#2683 chore: autogenerated discovery document update
  discoveries/file.v1.json
Labels: cla: yes, automerge

#2684 chore: autogenerated discovery document update
  discoveries/bigtableadmin.v2.json
  discoveries/prod_tt_sasportal.v1alpha1.json
Labels: cla: yes, automerge

#2685 chore: autogenerated discovery document update
  discoveries/people.v1.json
Labels: cla: yes, automerge

#2686 chore: autogenerated discovery document update
  discoveries/bigtableadmin.v1.json
Labels: cla: yes, automerge

#2687 chore: autogenerated discovery document update
  discoveries/reseller.v1.json
Labels: cla: yes, automerge

#2688 chore: autogenerated discovery document update
  discoveries/dlp.v2.json
Labels: cla: yes, automerge

#2689 chore: autogenerated discovery document update
  discoveries/cloudbuild.v1.json
  discoveries/youtube.v3.json
Labels: cla: yes, automerge

#2690 chore: autogenerated discovery document update
  discoveries/apigee.v1.json
  discoveries/cloudasset.v1.json
Labels: cla: yes, automerge

#2691 chore: autogenerated discovery document update
  discoveries/cloudidentity.v1.json
  discoveries/cloudidentity.v1beta1.json
Labels: cla: yes, automerge

#2692 chore: autogenerated discovery document update
  discoveries/cloudtasks.v2.json
  discoveries/retail.v2.json
Labels: cla: yes, automerge

#2693 chore: autogenerated discovery document update
  discoveries/retail.v2alpha.json
  discoveries/retail.v2beta.json
Labels: cla: yes, automerge

#2694 chore: autogenerated discovery document update
  discoveries/dataproc.v1beta2.json
  discoveries/index.json
Labels: cla: yes, automerge

#2695 chore: autogenerated discovery document update
  discoveries/cloudtasks.v2beta2.json
  discoveries/dataproc.v1beta2.json
  discoveries/index.json
Labels: cla: yes, automerge

#2696 chore: autogenerated discovery document update
  discoveries/cloudtasks.v2beta3.json
Labels: cla: yes, automerge

#2697 chore: autogenerated discovery document update
  discoveries/dataproc.v1beta2.json
  discoveries/index.json
Labels: cla: yes, automerge

#2698 chore: autogenerated discovery document update
  discoveries/dataproc.v1beta2.json
  discoveries/index.json
Labels: cla: yes, automerge

#2699 chore: autogenerated discovery document update
  discoveries/dataproc.v1beta2.json
  discoveries/index.json
Labels: cla: yes, automerge

#2700 chore: autogenerated discovery document update
  discoveries/videointelligence.v1.json
  discoveries/videointelligence.v1p2beta1.json
  discoveries/videointelligence.v1p3beta1.json
Labels: cla: yes, automerge

#2703 chore: autogenerated discovery document update
  discoveries/dataproc.v1beta2.json
  discoveries/documentai.v1.json
  discoveries/documentai.v1beta2.json
  discoveries/documentai.v1beta3.json
  discoveries/index.json
Labels: cla: yes, automerge

#2704 chore: autogenerated discovery document update
  discoveries/dataproc.v1beta2.json
  discoveries/index.json
  discoveries/mybusinesslodging.v1.json
  discoveries/videointelligence.v1beta2.json
  discoveries/videointelligence.v1p1beta1.json
Labels: cla: yes, automerge

#2705 chore: autogenerated discovery document update
  discoveries/dataproc.v1beta2.json
  discoveries/index.json
Labels: cla: yes, automerge

#2706 chore: autogenerated discovery document update
  discoveries/dataproc.v1beta2.json
  discoveries/index.json
Labels: cla: yes, automerge

#2707 chore: autogenerated discovery document update
  discoveries/dataproc.v1beta2.json
  discoveries/index.json
Labels: cla: yes, automerge

#2708 chore: autogenerated discovery document update
  discoveries/dataproc.v1beta2.json
  discoveries/index.json
Labels: cla: yes, automerge

#2709 chore: autogenerated discovery document update
  discoveries/bigquery.v2.json
  discoveries/dataproc.v1beta2.json
  discoveries/index.json
Labels: cla: yes, automerge

#2711 chore: autogenerated discovery document update
  discoveries/streetviewpublish.v1.json
Labels: cla: yes, automerge

#2712 chore: autogenerated discovery document update
  discoveries/accessapproval.v1.json
Labels: cla: yes, automerge

#2713 chore: autogenerated discovery document update
  discoveries/displayvideo.v1.json
Labels: cla: yes, automerge

#2714 chore: autogenerated discovery document update
  discoveries/sqladmin.v1.json
Labels: cla: yes, automerge

#2715 chore: autogenerated discovery document update
  discoveries/recommendationengine.v1beta1.json
  discoveries/sqladmin.v1beta4.json
Labels: cla: yes, automerge

#2716 chore: autogenerated discovery document update
  discoveries/dataproc.v1.json
Labels: cla: yes, automerge

#2717 chore: autogenerated discovery document update
  discoveries/dialogflow.v2beta1.json
Labels: cla: yes, automerge

#2718 chore: autogenerated discovery document update
  discoveries/dialogflow.v2.json
Labels: cla: yes, automerge

#2719 chore: autogenerated discovery document update
  discoveries/cloudprofiler.v2.json
Labels: cla: yes, automerge

#2720 chore: autogenerated discovery document update
  discoveries/memcache.v1.json
Labels: cla: yes, automerge

#2721 chore: autogenerated discovery document update
  discoveries/memcache.v1beta2.json
Labels: cla: yes, automerge

#2722 chore: autogenerated discovery document update
  discoveries/ideahub.v1beta.json
  discoveries/spanner.v1.json
Labels: cla: yes, automerge

#2723 chore: autogenerated discovery document update
  discoveries/spanner.v1.json
Labels: cla: yes, automerge

#2724 chore: autogenerated discovery document update
  discoveries/compute.v1.json
Labels: cla: yes, automerge

#2725 chore: autogenerated discovery document update
  discoveries/compute.beta.json
Labels: cla: yes, automerge

#2726 chore: autogenerated discovery document update
  discoveries/compute.alpha.json
Labels: cla: yes, automerge

#2727 chore: autogenerated discovery document update
  discoveries/adsense.v2.json
Labels: cla: yes, automerge

#2728 chore: autogenerated discovery document update
  discoveries/apigee.v1.json
Labels: cla: yes, automerge

#2729 chore: autogenerated discovery document update
  discoveries/streetviewpublish.v1.json
Labels: cla: yes, automerge

#2730 chore: autogenerated discovery document update
  discoveries/policyanalyzer.v1.json
Labels: cla: yes, automerge

#2747 chore: autogenerated discovery document update
  discoveries/content.v2.1.json
  discoveries/firebaseappcheck.v1beta.json
Labels: cla: yes, automerge

#2750 chore: autogenerated discovery document update
  discoveries/content.v2.json
Labels: cla: yes, automerge

#2751 chore: autogenerated discovery document update
  discoveries/pubsublite.v1.json
Labels: cla: yes, automerge

#2756 chore: autogenerated discovery document update
  discoveries/paymentsresellersubscription.v1.json
Labels: cla: yes, automerge

#2757 chore: autogenerated discovery document update
  discoveries/cloudasset.v1.json
  discoveries/documentai.v1.json
Labels: cla: yes, automerge

#2763 chore: autogenerated discovery document update
  discoveries/cloudasset.v1p5beta1.json
Labels: cla: yes, automerge

#2764 chore: autogenerated discovery document update
  discoveries/chat.v1.json
  discoveries/redis.v1.json
Labels: cla: yes, automerge

#2767 chore: autogenerated discovery document update
  discoveries/redis.v1beta1.json
  discoveries/sasportal.v1alpha1.json
Labels: cla: yes, automerge

#2784 chore: autogenerated discovery document update
  discoveries/containeranalysis.v1alpha1.json
  discoveries/containeranalysis.v1beta1.json
Labels: cla: yes, automerge

#2787 chore: autogenerated discovery document update
  discoveries/healthcare.v1.json
Labels: cla: yes, automerge

#2789 chore: autogenerated discovery document update
  discoveries/ondemandscanning.v1.json
Labels: cla: yes, automerge

#2790 chore: autogenerated discovery document update
  discoveries/bigqueryreservation.v1.json
  discoveries/bigqueryreservation.v1beta1.json
Labels: cla: yes, automerge

#2791 chore: autogenerated discovery document update
  discoveries/appengine.v1beta.json
Labels: cla: yes, automerge

#2792 chore: autogenerated discovery document update
  discoveries/androidmanagement.v1.json
  discoveries/run.v1alpha1.json
Labels: cla: yes, automerge

#2793 chore: autogenerated discovery document update
  discoveries/analyticsadmin.v1alpha.json
  discoveries/datastore.v1beta1.json
  discoveries/datastore.v1beta3.json
Labels: cla: yes, automerge

#2794 chore: autogenerated discovery document update
  discoveries/datastore.v1.json
Labels: cla: yes, automerge

#2795 chore: autogenerated discovery document update
  discoveries/youtube.v3.json
Labels: cla: yes, automerge

#2797 chore: autogenerated discovery document update
  discoveries/appengine.v1.json
Labels: cla: yes, automerge

#2796 feat: Allow manual overrides to specify deleting a language sample
  src/snippetgen/common/fragment/merge.go
Labels: priority: p2, cla: yes, samples

#2798 chore: autogenerated discovery document update
  discoveries/osconfig.v1.json
  discoveries/osconfig.v1alpha.json
  discoveries/sts.v1.json
Labels: cla: yes, automerge

#2799 chore: autogenerated discovery document update
  discoveries/storage.v1.json
Labels: cla: yes, automerge

#2800 chore: autogenerated discovery document update
  discoveries/container.v1.json
Labels: cla: yes, automerge

#2801 chore: autogenerated discovery document update
  discoveries/apigee.v1.json
  discoveries/customsearch.v1.json
Labels: cla: yes, automerge

#2802 chore: autogenerated discovery document update
  discoveries/clouderrorreporting.v1beta1.json
Labels: cla: yes, automerge

#2803 chore: autogenerated discovery document update
  discoveries/contactcenterinsights.v1.json
  discoveries/container.v1beta1.json
Labels: cla: yes, automerge

#2804 chore: autogenerated discovery document update
  discoveries/displayvideo.v1.json
  discoveries/storagetransfer.v1.json
Labels: cla: yes, automerge

#2805 chore: autogenerated discovery document update
  discoveries/bigquery.v2.json
  discoveries/sqladmin.v1.json
Labels: cla: yes, automerge

#2806 chore: autogenerated discovery document update
  discoveries/notebooks.v1.json
  discoveries/sqladmin.v1beta4.json
Labels: cla: yes, automerge

#2807 chore: autogenerated discovery document update
  discoveries/compute.beta.json
Labels: cla: yes, automerge

#2808 chore: autogenerated discovery document update
  discoveries/assuredworkloads.v1.json
Labels: cla: yes, automerge

#2811 chore: autogenerated discovery document update
  discoveries/cloudidentity.v1beta1.json
  discoveries/doubleclickbidmanager.v1.1.json
Labels: cla: yes, automerge

#2812 chore: autogenerated discovery document update
  discoveries/cloudidentity.v1.json
  discoveries/oslogin.v1.json
Labels: cla: yes, automerge

#2813 chore: autogenerated discovery document update
  discoveries/fitness.v1.json
Labels: cla: yes, automerge

#2814 chore: autogenerated discovery document update
  discoveries/storage.v1.json
Labels: cla: yes, automerge

#2815 chore: autogenerated discovery document update
  discoveries/healthcare.v1.json
  discoveries/healthcare.v1beta1.json
Labels: cla: yes, automerge

#2816 chore: autogenerated discovery document update
  discoveries/paymentsresellersubscription.v1.json
Labels: cla: yes, automerge

#2817 chore: autogenerated discovery document update
  discoveries/adexchangebuyer2.v2beta1.json
  discoveries/composer.v1.json
  discoveries/dialogflow.v2beta1.json
  discoveries/dialogflow.v3beta1.json
  discoveries/drive.v2.json
  discoveries/drive.v3.json
Labels: cla: yes, automerge

#2818 chore: autogenerated discovery document update
  discoveries/analyticsadmin.v1alpha.json
  discoveries/dialogflow.v2.json
  discoveries/dialogflow.v3.json
Labels: cla: yes, automerge

#2819 chore: autogenerated discovery document update
  discoveries/iam.v1.json
Labels: cla: yes, automerge

#2820 chore: autogenerated discovery document update
  discoveries/realtimebidding.v1alpha.json
Labels: cla: yes, automerge

#2821 chore: autogenerated discovery document update
  discoveries/monitoring.v1.json
Labels: cla: yes, automerge

#2822 chore: autogenerated discovery document update
  discoveries/appengine.v1beta.json
Labels: cla: yes, automerge

#2823 chore: autogenerated discovery document update
  discoveries/appengine.v1.json
Labels: cla: yes, automerge

#2824 chore: autogenerated discovery document update
  discoveries/area120tables.v1alpha1.json
Labels: cla: yes, automerge

#2825 chore: autogenerated discovery document update
  discoveries/firestore.v1.json
Labels: cla: yes, automerge

#2762 chore: Configure CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes

#2828 chore: autogenerated discovery document update
  discoveries/artifactregistry.v1.json
  discoveries/artifactregistry.v1beta1.json
  discoveries/artifactregistry.v1beta2.json
  discoveries/retail.v2.json
  discoveries/retail.v2alpha.json
Labels: cla: yes, automerge

#2829 chore: autogenerated discovery document update
  discoveries/retail.v2beta.json
Labels: cla: yes, automerge

#2830 chore: autogenerated discovery document update
  discoveries/gkehub.v1beta.json
Labels: cla: yes, automerge

#2831 chore: autogenerated discovery document update
  discoveries/gameservices.v1beta.json
  discoveries/gkehub.v1.json
  discoveries/gkehub.v1alpha.json
Labels: cla: yes, automerge

#2832 chore: autogenerated discovery document update
  discoveries/gameservices.v1.json
Labels: cla: yes, automerge

#2833 chore: autogenerated discovery document update
  discoveries/spanner.v1.json
Labels: cla: yes, automerge

#2834 chore: autogenerated discovery document update
  discoveries/metastore.v1alpha.json
  discoveries/metastore.v1beta.json
Labels: cla: yes, automerge

#2835 chore: autogenerated discovery document update
  discoveries/content.v2.1.json
Labels: cla: yes, automerge

#2836 chore: autogenerated discovery document update
  discoveries/composer.v1beta1.json
Labels: cla: yes, automerge

#2837 chore: autogenerated discovery document update
  discoveries/composer.v1.json
Labels: cla: yes, automerge

#2838 chore: autogenerated discovery document update
  discoveries/apigee.v1.json
  discoveries/servicenetworking.v1.json
Labels: cla: yes, automerge

#2839 chore: autogenerated discovery document update
  discoveries/documentai.v1.json
  discoveries/documentai.v1beta3.json
Labels: cla: yes, automerge

#2840 chore: autogenerated discovery document update
  discoveries/networkmanagement.v1.json
  discoveries/networkmanagement.v1beta1.json
Labels: cla: yes, automerge

#2841 chore: autogenerated discovery document update
  discoveries/firebaseappcheck.v1beta.json
  discoveries/index.json
  discoveries/networkconnectivity.v1.json
Labels: cla: yes, automerge

#2842 chore: autogenerated discovery document update
  discoveries/contactcenterinsights.v1.json
Labels: cla: yes, automerge

#2843 chore: autogenerated discovery document update
  discoveries/cloudidentity.v1.json
  discoveries/cloudidentity.v1beta1.json
Labels: cla: yes, automerge

#2844 chore: autogenerated discovery document update
  discoveries/adexchangebuyer.v1.2.json
  discoveries/adexchangebuyer.v1.3.json
  discoveries/adexchangebuyer.v1.4.json
  discoveries/cloudasset.v1.json
  discoveries/index.json
Labels: cla: yes, automerge

#2845 chore: autogenerated discovery document update
  discoveries/index.json
Labels: cla: yes, automerge

#2846 chore: autogenerated discovery document update
  discoveries/admin.directory_v1.json
  discoveries/index.json
Labels: cla: yes

#2847 chore: autogenerated discovery document update
  discoveries/index.json
Labels: cla: yes, automerge

#2848 chore: autogenerated discovery document update
  discoveries/cloudsearch.v1.json
Labels: cla: yes, automerge

#2849 chore: autogenerated discovery document update
  discoveries/index.json
Labels: cla: yes, automerge

#2850 chore: autogenerated discovery document update
  discoveries/index.json
Labels: cla: yes, automerge

#2851 chore: autogenerated discovery document update
  discoveries/index.json
Labels: cla: yes, automerge

#2852 chore: autogenerated discovery document update
  discoveries/index.json
Labels: cla: yes, automerge
